spring:
  application:
    name: help-desk
  datasource:
    url: jdbc:postgresql://localhost:5433/helpdesk
    username: helpdesk
    password: helpdesk
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: always
